add_newline = false
command_timeout = 1000

format = """
$character\
[î‚¼](bg:#222222)\
[â–ˆ](fg:#222222 )\
$directory\
[â–ˆî‚¼](fg:#222222 )\
$fill\
[$git_branch\
$git_state\
$git_status](bold bg:#111111 fg:white)\
$cmd_duration\
[î‚¶](fg:red bg:#111111)\
[ï€‡ ](fg:#111111 bg:red)\
$username\
[î‚¶](fg:green bg:#222222)\
[ó°Œ½ ](fg:green bg:#111111 inverted)\
$hostname\
$line_break\
[ â¯ ](fg:bright-white)"""

[character]
format = "$symbol"
error_symbol = "[ â–ˆ](fg:red)[ï‹“ ERROR](fg:black bg:red)[î‚¼](fg:red bg:white)"
success_symbol = "[ â–ˆ](fg:green)[î• PROMPT](fg:black bg:green)[î‚¼](fg:green bg:white)"

[fill]
symbol = ' '

[package]
disabled = false

[cmd_duration]
min_time = 1000
show_milliseconds = false
disabled = false
format="[ó°Œ $duration ]($style)"
style="bold bg:#111111"

[directory]
truncation_length = 5
format = "[ó°‰‹ $path]($style)[$lock_symbol]($lock_style)"
style = "bold fg:white bg:#222222"
read_only = "ğŸ”’"
read_only_style= "bold white"

[username]
show_always = true
style_user = "bg:#222222"
style_root = "bg:#222222"
format = '[ $user ]($style)'

[hostname]
format = "[ $hostname ]($style)"
ssh_only = false
trim_at = ".companyname.com"
disabled = false
style = "fg:green bg:#222222"

[git_commit]
commit_hash_length = 8
style = "bold white"

[status]
style = "bg:transparent"
symbol = "ğŸ’¥ "
format = '($style)'
disabled = false

[git_branch]
format = " ó°˜¬ $branch"
style = "bold fg:green bg:#111111"

[git_status]
format = " $conflicted$untracked$modified$staged$renamed$deleted$ahead_behind$stashed"
style = "cyan"
conflicted = ""
untracked = ""
modified = ""
staged = ""
renamed = ""
deleted = ""
stashed = "â‰¡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "cyan"

